server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # 跳过ssl认证
          skipSslValidation: true
          # git配置中心地址
          uri: https://github.com/2966325911/springcloud-config.git
          search-paths:
            - springcloud-config
      #读取分支名称
      label: master
  #rabbitmq相关配置，15672是web管理端口，web界面访问采用15672 ，5672是mq访问端口
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
