server:
  port: 7001

eureka:
  instance:
    # 本地 127.0.0.1 在hosts文件中配置
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eureka交互的查询服务和注册服务都需要依赖这个地址 ，集群需要相互守望
      # 1 注册2的地址 2注册1的地址
      defaultZone: http://eureka7002.com:7002/eureka/