server:
  port: 80

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
#开启feign的hystrix服务
feign:
  hystrix:
    enabled: true